set(CompilerFlags
  CMAKE_CXX_FLAGS
  CMAKE_CXX_FLAGS_DEBUG_INIT
  CMAKE_CXX_FLAGS_RELEASE_INIT
  CMAKE_CXX_FLAGS_DEBUG
  CMAKE_CXX_FLAGS_RELEASE
  CMAKE_CXX_FLAGS_MINSIZEREL
  CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT
  CMAKE_CXX_FLAGS_RELWITHDEBINFO
  CMAKE_C_FLAGS
  CMAKE_C_FLAGS_DEBUG_INIT
  CMAKE_C_FLAGS_RELEASE_INIT
  CMAKE_C_FLAGS_DEBUG
  CMAKE_C_FLAGS_RELEASE
  CMAKE_C_FLAGS_MINSIZEREL
  CMAKE_C_FLAGS_RELWITHDEBINFO_INIT
  CMAKE_C_FLAGS_RELWITHDEBINFO
  CMAKE_CUDA_FLAGS
  CMAKE_CUDA_FLAGS_DEBUG_INIT
  CMAKE_CUDA_FLAGS_RELEASE_INIT
  CMAKE_CUDA_FLAGS_DEBUG
  CMAKE_CUDA_FLAGS_RELEASE
  CMAKE_CUDA_FLAGS_MINSIZEREL
  CMAKE_CUDA_FLAGS_RELWITHDEBINFO_INIT
  CMAKE_CUDA_FLAGS_RELWITHDEBINFO)

foreach(CompilerFlag ${CompilerFlags})
  string(REPLACE "/MD" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
  string(REPLACE "-MD" "-MT" ${CompilerFlag} "${${CompilerFlag}}")
  string(REPLACE "/MTd" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
  string(REPLACE "/MTd" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
endforeach()
